-- MySQL Script generated by MySQL Workbench
-- 07/13/16 23:31:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

--SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
--SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
--SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `job`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `job` (
  `idjob` INT NOT NULL ,
  `job` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idjob`));


-- -----------------------------------------------------
-- Table `contacttype`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `contacttype` (
  `idcontacttype` INT NOT NULL,
  `contacttype` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idcontacttype`));


-- -----------------------------------------------------
-- Table `maritalstatus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `maritalstatus` (
  `idmaritalstatus` INT NOT NULL,
  `status` VARCHAR(10) NULL,
  PRIMARY KEY (`idmaritalstatus`));


-- -----------------------------------------------------
-- Table `client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `client` (
  `idclient` INT NOT NULL,
  `age` INT NULL,
  `marital_status` INT NULL,
  `idjob` INT NULL,
  `contact_type` INT NULL,
  PRIMARY KEY (`idclient`),
  CONSTRAINT `jobid`
    FOREIGN KEY (`idjob`)
    REFERENCES `job` (`idjob`),
  CONSTRAINT `contact_type`
    FOREIGN KEY (`contact_type`)
    REFERENCES `contacttype` (`idcontacttype`),
  CONSTRAINT `marital_status`
    FOREIGN KEY (`marital_status`)
    REFERENCES `maritalstatus` (`idmaritalstatus`)
    );


-- -----------------------------------------------------
-- Table `bank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bank` (
  `housing` BINARY NULL,
  `loan` BINARY NULL,
  `idclient` INT NOT NULL,
  PRIMARY KEY (`idclient`),
  CONSTRAINT `clientId`
    FOREIGN KEY (`idclient`)
    REFERENCES `client` (`idclient`)
    );


-- -----------------------------------------------------
-- Table `incometax`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `incometax` (
  `year` INT NOT NULL,
  `incometaxrate` FLOAT NOT NULL,
  PRIMARY KEY (`year`));


-- -----------------------------------------------------
-- Table `economic_factor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `economic_factor` (
  `consumer_confidence_index` FLOAT NULL,
  `consumer_price_index` FLOAT NULL,
  `emp.var.rate` FLOAT NULL,
  `euribor_rate` FLOAT NULL,
  `nr.employed` INT NULL,
  `Inflation.rate` FLOAT NULL,
  `euribor.rate` FLOAT NULL,
  `month` INT NOT NULL,
  `year` INT NOT NULL,
  PRIMARY KEY (`month`, `year`),
  CONSTRAINT `year`
    FOREIGN KEY (`year`)
    REFERENCES `incometax` (`year`)
    );

-- -----------------------------------------------------
-- Table `campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `campaign` (
  `day` INT NULL,
  `duration` INT NULL,
  `previous_contacts` INT NULL,
  `pdays` INT NULL,
  `campaign_contacts` INT NULL,
  `outcome` BINARY NULL,
  `previous_outcome` BINARY NULL,
  `idclient` INT NOT NULL,
  `month` INT NULL,
  `year` INT NULL,
  PRIMARY KEY (`idclient`),
  CONSTRAINT `clientid`
    FOREIGN KEY (`idclient`)
    REFERENCES `client` (`idclient`),
  CONSTRAINT `month`
    FOREIGN KEY (`month`)
    REFERENCES `economic_factor` (`month`),
  CONSTRAINT `year`
    FOREIGN KEY (`year`)
    REFERENCES `economic_factor` (`year`)
    );
--SET SQL_MODE=@OLD_SQL_MODE;
--SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
--SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
